---

- name: Create systemd file for value node
  template:
    src: "systemd/{{chain_node_type}}_value_node.service.j2"
    dest: "{{ systemd_files_path }}/{{chain_node_type}}_vn.service"

- name: Generate new bootnod key and use it
  become_user: "{{ deploy_user }}"
  shell: |
    cd {{ vc_node_dir }};
    bootnode_exe=/opt/go-ethereum/build/bin/bootnode;
    ${bootnode_exe} -genkey bootnode.key
    cat bootnode.key > node_v/geth/nodekey

- name: Start value geth node
  systemd:
    name: "{{chain_node_type}}_vn"
    daemon_reload: yes
    state: restarted
    enabled: yes


