---

server_type: nodejs
is_web: false

flush_memcache: True
flush_redis: True



nginx:
  worker_processes: 5
  listen_port: 8085
  logs_dir: "{{ logs_dir }}/nginx"
  pid_dir: "{{pid_dir}}"
  rate_limit:
    zone_size: 30m
    rate: "300r/s"
    burst_size: 50
    delay: 30
    limit_key: "$remote_addr"
  realip_from:
    - 121.141.0.0/20
    - 121.141.64.0/20
    - 121.142.0.0/20
    - 121.142.64.0/20
  es:
    listen_port: 8087
    domain: es.stagingost.com
    basic_auth_file: /home/deployer/libs/nginx/conf/.es_htpasswd
    proxy_domain: vpc-saas-api-staging-seds4tuzkvah7asvpmuo4vpj7u.us-east-1.es.amazonaws.com




pagerduty:
  cron_time_in_minute: "*/5"
  geth_block_check_time_interval: "300"
