---

chain_node_type: 'geth'

utility_node_sync_port: 30301
utility_node_rpcport: 8541
utility_node_wsport: 8551
utility_node_targetgaslimit: 150000000

geth_node_id: "node_u"

# Local operation vars
local_temp_env_file: temp_env_vars.sh

server_type: 'nginx'

nginx:
  worker_processes: 5
  listen_port: 8096
  logs_dir: "{{ logs_dir }}/nginx"
  pid_dir: "{{pid_dir}}"
  rate_limit:
    burst_size: 50
    delay: 30
    zone_size: 30m
    rate: "300r/s"
    limit_key: "$remote_addr"
  realip_from:
    - 10.49.0.0/20
    - 10.49.64.0/20
    - 10.50.0.0/20
    - 10.50.64.0/20
  whitelisted_ips:
    - 114.143.238.58
    - 174.138.2.174
    - 10.50.0.0/16
    - 10.49.0.0/16
    - 103.218.253.218


pagerduty:
  cron_time_in_minute: "*/5"
  geth_block_check_time_interval: 5
  geth_tx_pool_threshold: 100
  geth_open_files_threshold: 100
